# IFS highlights

Assorted research highlights from my nine years or so (2017 -- 2026) at the [Institute for Fiscal Studies](https://ifs.org.uk/){target="_blank"}. 

## Fiscal traffic lights 

This is probably the piece of IFS work I'm most proud of: an analysis of the problems with the UK's approach to fiscal policy and a detailed proposal for what an alternative fiscal framework could look like. 

[**From fiscal rules to fiscal traffic lights: rethinking the UK fiscal framework**](https://ifs.org.uk/publications/fiscal-rules-fiscal-traffic-lights-rethinking-uk-fiscal-framework){target="_blank"}, IFS, February 2026.  

Watch (or [listen to](https://open.spotify.com/episode/5VZFnCE23YE5tG5FXIKUCX?si=9fW4Gg_RQVuPVKXzsIrKLw){target="_blank"}) a discussion the proposals with Helen Miller on the IFS Zooms In podcast: [https://www.youtube.com/watch?v=XmeGpSaQ9YA](https://www.youtube.com/watch?v=XmeGpSaQ9YA){target="_blank"}   

And/or watch me present the key findings and recommendations at an event at the Royal Society, followed by a panel discussion with Rupert Harrison, Victoria Clarke and Chris Giles, chaired by Gus O'Donnell: [https://www.youtube.com/watch?v=l_quJWjDc1E](https://www.youtube.com/watch?v=l_quJWjDc1E){target="_blank"} 

I wrote about the research for The Observer [here](https://observer.co.uk/news/business/article/fiscal-rules-arent-working-we-need-a-new-traffic-light-system-to-show-the-way){target="_blank"}. 

Selected other media coverage: [Financial Times](https://www.ft.com/content/c88bc54b-2957-4ada-ab1b-bb397e11eaf1){target="_blank"}, [BBC](https://www.bbc.co.uk/news/articles/c1kg48m937wo){target="_blank"}, [Telegraph](https://www.telegraph.co.uk/business/2026/02/19/ditch-fiscal-rules-dysfunctional-britain-treasury-urged/){target="_blank"}, [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-19/uk-budget-headroom-has-become-a-harmful-obsession-ifs-warns){target="_blank"}, [Reuters](https://www.reuters.com/world/uk/uk-should-drop-fiscal-goals-new-traffic-light-system-ifs-says-2026-02-19/){target="_blank"}. 

## Other work on fiscal policy 

I've published on a wide range of other fiscal policy topics. Some selected highlights include:

- [**A note of caution on fiscal technocracy**](https://ifs.org.uk/articles/note-caution-fiscal-technocracy){target="_blank"}, IFS, May 2024 - an argument that we should be cautious about handing over greater powers over fiscal policy to unelected technocrats. 
- [**Public investment: what you need to know**](https://ifs.org.uk/articles/public-investment-what-you-need-know){target="_blank"}, IFS, April 2024 - an explainer and discussion of the key policy and measurement issues related to public investment. 
- [**Public sector net worth as a fiscal target**](https://ifs.org.uk/publications/public-sector-net-worth-fiscal-target){target="_blank"}, IFS Green Budget, October 2023 - an exploration of the pros and cons (mainly cons) of targeting public sector net worth.  
- [**Chancellors’ responses to economic news**](https://ifs.org.uk/publications/chancellors-responses-economic-news){target="_blank"} (with Carl Emmerson, Isabel Stockton and Sam van de Schootbrugge), IFS Green Budget, September 2023 - analysis demonstrating that Chancellors react asymmetrically to economic shocks, a pattern which leads to higher debt and a bigger state, and which means that the OBR's central forecast isn't central in practice. 
- [**Public spending, pay and pensions**](https://ifs.org.uk/publications/public-spending-pay-and-pensions){target="_blank"} (with Bee Boileau and Laurence O'Brien), IFS Green Budget, October 2022 - includes, among other things, analysis of public-private differentials in pay and pensions. 
- [**The planning and control of UK public expenditure, 1993-2015**](https://ifs.org.uk/publications/planning-and-control-uk-public-expenditure-1993-2015){target="_blank"} (with Rowena Crawford and Paul Johnson), IFS, July 2018 - my first ever project at IFS, which contributed to a subsequent project (and [book](https://global.oup.com/academic/product/the-way-the-money-goes-9780198865087){target="_blank"}) on the UK spending framework, led by the late Christopher Hood. 
- The [**IFS Be the Chancellor**](https://ifs.org.uk/be-chancellor){target="_blank"} tool, which lets you alter plans for tax and public spending, and see the impact on the public finances. 
- Persuading the BBC to pronounce PSNFL as "persnuffle" on [More or Less](https://www.bbc.co.uk/programmes/p0jwdkrk){target="_blank"}.
- This four-part podcast series on how to fix the UK tax system (parts [one](https://ifs.org.uk/articles/how-fix-income-tax){target="_blank"}, [two](https://ifs.org.uk/articles/how-fix-wealth-taxes){target="_blank"}, [three](https://ifs.org.uk/articles/how-fix-property-taxes){target="_blank"}, and [four](https://ifs.org.uk/articles/how-fix-vat){target="_blank"}), recorded with Helen Miller and Stuart Adam. I played the role of useful idiot. 
- Various editions of the [**IFS Green Budget**](https://ifs.org.uk/ifs-green-budget){target="_blank"}, the flagship annual publication analysing the options and challenges facing the Chancellor ahead of the Budget. I was one of the editors in 2021, 2022, 2023 and 2025.

## Public sector productivity 

To my knowledge, this report (co-authored with Max Warner in December 2022) was the first to draw attention to the pronounced reduction in NHS productivity after the pandemic: [**NHS funding, resources and treatment volumes**](https://ifs.org.uk/publications/nhs-funding-resources-and-treatment-volumes){target="_blank"}. 

I summarised the findings in this X/Twitter [thread](https://x.com/BenZaranko/status/1602935890036269057?s=20){target="_blank"} and discussed the report on [BBC More or Less](t.co/Id2HNpMIQz){target="_blank"} with Tim Harford. (I've also been on More or Less to discuss [Baumol's cost disease](https://www.bbc.co.uk/programmes/p0jr54c5){target="_blank"} and how [NHS productivity](https://www.bbc.co.uk/sounds/play/m002phn1) is performing in more recent data). It was covered in various other media oulets but I don't have the links so you'll just have to take my word for it. 

Other analyses of public sector productivity include:

- [**Productivity in the Crown Court**](https://ifs.org.uk/publications/productivity-crown-court){target="_blank"} (with Magdalena Dominguez and Joe Tomlinson), IFS, June 2025 - an exploration of whether falling productivity (i.e. a slowdown in the rate at which cases are disposed of) could explain the increase in the Crown Court backlog of England and Wales.
- [**NHS hospital productivity: some positive news**](https://ifs.org.uk/articles/nhs-hospital-productivity-some-positive-news ){target="_blank"} (with Olly Harvey-Rich and Max Warner), IFS, November 2024 - highlighting emerging signs of a productivity recovery in English NHS hospitals. 
- [**The fiscal implications of public service productivity**](https://ifs.org.uk/publications/fiscal-implications-public-service-productivity){target="_blank"} (with Max Warner), IFS, May 2024 - some analysis drawning out what changes in public service productivity mean for the amount of spending on those services. 
- [**Is there really an NHS productivity crisis?**](https://ifs.org.uk/articles/there-really-nhs-productivity-crisis){target="_blank"} (with Max Warner), IFS, November 2023 - a short piece responding to some comments from the then-NHS England CEO. Figure 1 is a blinder.   

## Health and social care 

I've published analysis of various aspects of the UK health and social care system, including:

- [**The relationship between NHS waiting lists and health-related benefit claims**](https://ifs.org.uk/publications/relationship-between-nhs-waiting-lists-and-health-related-benefit-claims){target="_blank"} (with Max Warner), IFS, May 2025 - exploring whether longer waiting lists/times for NHS hospital treatment could explain recent increases in health-related benefit claims (short answer: no, probably not). 
- [**Adult social care in England: what next?**](https://ifs.org.uk/publications/adult-social-care-england-what-next){target="_blank"} (with Antonella Bancalari), IFS Green Budget, October 2024 - a whistlestop tour of the numerous, overlapping challenges facing the adult social care sector in England and the choices the government faces in tackling them. 
- [**Implications of the NHS workforce plan**](https://ifs.org.uk/publications/implications-nhs-workforce-plan){target="_blank"} (with Max Warner), IFS Green Budget, August 2023 - an analysis of what the NHS England workforce plan implies for spending on the NHS and the numbers working within it. 
- George Stoye, Max Warner and I won the [**2022 Harding Prize for Trustworthy Communication**](https://ifs.org.uk/news/ifs-nhs-waiting-lists-calculator-wins-2022-harding-prize-trustworthy-communication){target="_blank"} for our [interactive NHS waiting lists calculator](https://ifs.org.uk/calculators/what-could-happen-nhs-waiting-lists-england){target="_blank"}. 

## Academic research 

### Publications
- [**Nurse shortages and patient outcomes**](https://www.sciencedirect.com/science/article/pii/S0167629625001171?via%3Dihub) (with Elaine Kelly and Carol Propper), *Journal of Health Economics*, Vol. 105, January 2026.
- [**Future challenges for health and social care provision in the UK**](https://academic.oup.com/oxrep/article/41/1/179/8157937){target="_blank"} (with Max Warner), invited contribution to *Oxford Review of Economic Policy*, Vol. 41(1), June 2025.
- [**Nurse staffing and inpatient mortality in the English NHS**](https://qualitysafety.bmj.com/content/32/5/254){target="_blank"} (with Natalie Sanford, Elaine Kelly, Anne Marie Rafferty, James Bird, Luca Mercuri, Janice Sigsworth, Mary Wells and Carol Propper), *BMJ Quality & Safety*, September 2022.
- [**Long-term care spending and hospital use among the older population in England**](https://www.sciencedirect.com/science/article/pii/S016762962100062X?via%3Dihub){target="_blank"} (with Rowena Crawford and George Stoye), *Journal of Health Economics*, Vol. 78, July 2021.
- [**Educational inequalities in hospital use among older adults in England, 2004−2015**](https://onlinelibrary.wiley.com/doi/10.1111/1468-0009.12479){target="_blank"} (with George Stoye, Martin Shipley, Martin McKee and Eric Brunner), *The Milbank Quarterly*, October 2020.
- [**The wider impacts of the coronavirus pandemic on the NHS**](https://onlinelibrary.wiley.com/doi/10.1111/1475-5890.12227){target="_blank"} (with Carol Propper and George Stoye), invited contribution to *Fiscal Studies*, Vol. 41(2), June 2020. 

### Working papers 
- [**Off to the shops? Outside job opportunities and care worker labour supply**](https://ifs.org.uk/publications/shops-outside-job-opportunities-and-care-worker-labour-supply){target="_blank"} (with Max Warner), *IFS Working Paper WP25/61*, December 2025.
- [**How accurate are self-reported diagnoses? Comparing self-reported health events in the English Longitudinal Study of Ageing with administrative hospital records**](https://ifs.org.uk/publications/how-accurate-are-self-reported-diagnoses-comparing-self-reported-health-events-english){target="_blank"} (with George Stoye), *IFS Working Paper WP20/13*, May 2020.
