---
title: "Ben Zaranko"
---
I'm an economist and Associate Director at the [Institute for Fiscal Studies](https://ifs.org.uk/){target="_blank"} (IFS) in London. 

I lead IFS work on the public finances. Between 2021 and 2023 and again in 2025, I was co-editor of the [IFS Green Budget](https://ifs.org.uk/ifs-green-budget){target="_blank"}, the Institute's flagshp annual publication. I have published research across a range of economic and fiscal policy issues, including academic work on the performance, productivity and distributional implications of the health care system. 

I have discussed my research in more than 200 broadcast interviews, I write a regular column for [The Observer](https://observer.co.uk/contributor/ben-zaranko){target="_blank"}, and I have given evidence to three parliamentary select committees. 

I hold undergraduate and masters degrees in economics from the University of Oxford and University College London, respectively. You can find a copy of my CV here [PDF link to be added]. 

[Download academic CV](Ben Zaranko Academic CV February 2026.pdf){target="_blank"} 
[IFS profile and output list](https://ifs.org.uk/people/ben-zaranko){target="_blank"} 
[Google Scholar](https://scholar.google.com/citations?user=JalUHmkAAAAJ&hl=en){target="_blank"} 