## Columns for *The Observer*

You can find a full list of my pieces for *The Observer* (behind a paywall) [here](https://observer.co.uk/contributor/ben-zaranko){target="_blank"}. Some of my favourites among those: 

- [**Why students are choosing payslips over passion**](https://observer.co.uk/news/national/article/why-students-are-choosing-payslips-over-passion){target="_blank"}, August 2026
-  [**Reality check for Trumponomics as world’s biggest economy is exposed**](https://observer.co.uk/news/international/article/reality-check-for-trumponomics-as-worlds-biggest-economy-is-exposed){target="_blank"}, August 2026
-  [**Remember: immigrants create jobs as well as take them**](https://observer.co.uk/news/national/article/remember-immigrants-create-jobs-as-well-as-take-them){target="_blank"}, August 2026
- [**What do universities and house builders have in common? Neither can cut headline prices**](https://observer.co.uk/news/business/article/what-do-universities-and-house-builders-have-in-common-neither-can-cut-headline-prices){target="_blank"}, August 2026
- [**Why economists need to be better storytellers**](https://observer.co.uk/news/opinion-and-ideas/article/why-economists-need-to-be-better-storytellers){target="_blank"}, August 2026
- [**Delivering a national care service is easier said than done**](https://observer.co.uk/news/national/article/delivering-a-national-care-service-is-easier-said-than-done){target="_blank"}, August 2026
- [**Social care in numbers: Burnham has a gargantuan task ahead of him**](https://observer.co.uk/news/national/article/social-care-in-numbers-burnham-has-a-gargantuan-task-ahead-of-him){target="_blank"}, August 2026
- [**Why don't Gen Z buy rounds in the pub?**](https://observer.co.uk/news/business/article/why-dont-gen-z-buy-rounds-in-the-pub){target="_blank"}, July 2026
- [**Taking policy tips from Peep Show’s Jeremy is no recipe for success**](https://observer.co.uk/news/politics/article/taking-policy-tips-from-peep-shows-jeremy-is-no-recipe-for-success){target="_blank"}, July 2026
- [**Active support or tough love? Whatever you call it, it could be the answer to the youth Neets crisis**](https://observer.co.uk/news/business/article/youth-neets-crisis-education-employment-training-sunderland){target="_blank"}, July 2026
- [**How do the economists rate Reeves’s time at No 11?**](https://observer.co.uk/news/politics/article/how-do-the-economists-rate-reevess-time-at-no-11){target="_blank"}, July 2026
- [**The case for raising tax on older people**](https://observer.co.uk/news/business/article/the-case-for-raising-taxes-on-older-people){target="_blank"}, July 2026
- [**“Buying British” could be smart politics but poor economics**](https://observer.co.uk/news/business/article/buying-british-could-be-smart-politics-but-poor-economics){target="_blank"}, July 2026
- [**Here’s how Andy Burnham’s devolution revolution could drive growth**](https://observer.co.uk/news/business/article/heres-how-andy-burnhams-devolution-revolution-could-drive-growth){target="_blank"}, July 2026
- [**Mopping up the Thames Water mess will be an early test for Andy Burnham**](https://observer.co.uk/news/business/article/mopping-up-the-thames-water-mess-will-be-an-early-test-for-burnham){target="_blank"}, June 2026
- [**War bonds are back on the agenda, but history urges caution**](https://observer.co.uk/news/columnists/article/war-bonds-are-back-on-the-agenda-but-history-urges-caution){target="_blank"}, June 2026
- [**A review of *How To Win A Trade War*, by Soumaya Keynes and Chad Bown**](https://observer.co.uk/culture/books/article/a-survival-guide-for-the-age-of-trade-warfare){target="_blank"}, June 2026
- [**What’s the future for jobs? AI won’t replace messy roles or the human touch**](https://observer.co.uk/news/business/article/future-jobs-ai-wont-replace-messy-roles-or-the-human-touch){target="_blank"}, June 2026
- [**Downsizing isn’t yet in Richard’s interest. That needs to change**](https://observer.co.uk/news/business/article/downsizing-isnt-yet-in-richards-interest-that-needs-to-change){target="_blank"}, June 2026 (Richard being someone who Retired In a Comfortable House And Refuses to Downsize)
- [**Broadband and mobile bills are soaring in the UK – depending on who you talk to**](https://observer.co.uk/news/business/article/broadband-and-mobile-bills-are-soaring-in-the-uk-depending-on-who-you-talk-to){target="_blank"}, May 2026 (inspired by a [bonkers chart](https://x.com/BenZaranko/status/2060637675023982904?s=20){target="_blank"})
- [**Why Labour is making labour more costly**](https://observer.co.uk/news/business/article/why-labour-is-making-labour-more-costly){target="_blank"}, May 2026
- [**The battle for the future of Labour’s economic vision has begun**](https://observer.co.uk/news/politics/article/the-battle-for-the-future-of-labours-economic-vision-has-begun){target="_blank"}, May 2026
- [**Serenity, courage and wisdom: the government's path to economic growth**](https://observer.co.uk/news/capital/article/the-alcoholics-anonymous-prayer-that-could-make-britain-richer){target="_blank"}, May 2026
- [**Why we should mind the UK’s rising wealth gap**](https://observer.co.uk/news/capital/article/why-we-should-mind-the-uks-rising-wealth-gap){target="_blank"}, May 2026
- [**Hedge funds have bet big on our bonds, and it’s a gamble that could cost us dear**](https://observer.co.uk/news/business/article/ben-zaranko-hedge-funds-have-bet-big-on-our-bonds-and-its-a-gamble-that-could-cost-us-dear){target="_blank"}, April 2026
- [**A profile of Kevin Warsh**](https://observer.co.uk/news/profile/article/kevin-warsh-banker-tipped-for-most-important-role-in-global-finance){target="_blank"}, April 2026
- [**The great UK unemployment debate**](https://observer.co.uk/news/national/article/the-great-uk-unemployment-debate){target="_blank"}, March 2026
- [**UK risks shooting itself in the foot on defence**](https://observer.co.uk/news/national/article/uk-risks-shooting-itself-in-the-foot-on-defence){target="_blank"}, January 2026
- [**In Britain’s ‘hedgehog economy’, growth is wild, spiky – and fragile**](https://observer.co.uk/news/business/article/in-britains-hedgehog-economy-growth-is-wild-spiky-and-fragile){target="_blank"}, October 2025
- [**Remember, remember Liz Truss this November**](https://observer.co.uk/news/politics/article/what-reeves-must-remember-this-november-about-liz-trusss-mini-budget){target="_blank"}, September 2025

## Other writing

- [**We should be wary of a fiscal technocracy**](https://www.thetimes.com/article/we-should-be-wary-of-a-fiscal-technocracy-3bqdwd5rr?gaa_at=eafs&gaa_n=AWEtsqeXBMB-qb_9_GWLkcex_6Hr_d5OB5s9ADvilSnnS45EYtne8twgB7RGfTiArd0%3D&gaa_ts=699b555e&gaa_sig=muigO0XidsznRdwu7MBZWV97JheUzfHZLWsy-BxBO71Q9QP7hXGfuw2d3yMmPWpQyTp1lr0OXWMxQM5vvpGqjw%3D%3D){target="_blank"}, *The Times (£)*, May 2024.
- [**As the state gets bigger, taxes will rise. It’s time to be honest about that**](https://www.prospectmagazine.co.uk/ideas/economics/61116/as-the-state-gets-bigger-taxes-will-rise.-its-time-to-be-honest-about-that){target="_blank"}, *Prospect Magazine*, April 2023.
- [**Defence cuts effectively paid for UK welfare state for 60 years – but that looks impossible after Ukraine**](https://theconversation.com/defence-cuts-effectively-paid-for-uk-welfare-state-for-60-years-but-that-looks-impossible-after-ukraine-178680){target="_blank"}, *The Conversation*, March 2022. 